runtime: python
env: flex
entrypoint: gunicorn -b :$PORT mysite.wsgi

runtime_config:
  python_version: 3.5

beta_settings:
    cloud_sql_instances: learndjango-197901:us-east1:learndjango-pg
  
env_variables:
  DEPLOYMENT: "PRODUCTION"

scripts:
  - ./manage.py migrate